# Generated by Django 4.0.6 on 2022-07-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('release_date', models.DateField()),
                ('main_actors', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=300)),
                ('synopsis', models.TextField(max_length=1000)),
                ('poster', models.ImageField(null=True, upload_to='movie_posters/')),
                ('trailer', models.CharField(max_length=300)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField()),
                ('profile_image', models.ImageField(upload_to='user_images/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
