# Generated by Django 4.0.6 on 2022-07-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviestation', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='cinemana', max_length=300),
        ),
    ]
